turismo/pagina/urls.py
from django.urls import path
from . import views


app_name = 'pagina'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('calendario/', views.Calendario.as_view(), name='calendario'),
    path('proveedor/', views.Proveedor.as_view(), name='proveedor'),
    path('feedback/clientes/', views.FeedbackClientesView.as_view(), name='feedback-clientes'),
    path('feedback/proveedores/', views.FeedbackProveedoresView.as_view(), name='feedback-proveedores'),

]

turismo/turismo/urls.py
from django.contrib import admin
from django.urls import path, include
from core.admin import admin_general

urlpatterns = [
    path('admin/', admin_general.urls),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),

    path('', include('pagina.urls', namespace='home')),
    path('', include('pwa.urls'))
]

turismo/asistencia/models.py
from django.db import models
from django.utils import timezone

from proveedor.models import ProveedorServicio
from capacitacion.models import Capacitacion


class Asistencia(models.Model):
    fecha = models.DateTimeField(default=timezone.now)
    descripcion = models.TextField(null=True, blank=True)
    proveedor = models.ManyToManyField(ProveedorServicio)
    capacitacion = models.ForeignKey(Capacitacion, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.fecha)

turismo/capacitacion/models.py
from django.db import models

from util.models import AbstractDireccion


class Capacitacion(AbstractDireccion):
    class Meta:
        verbose_name_plural = 'Capacitaciones'

    nombre = models.CharField(max_length=250)
    inicio = models.DateTimeField(null=True, blank=True)
    fin = models.DateTimeField(null=True, blank=True)
    horas = models.TimeField()
    puntos_incrementar = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nombre

turismo/core/models.py
from django.db import models

# Create your models here.

turismo/pagina/models.py
from django.db import models
from proveedor.models import ProveedorServicio
from capacitacion.models import Capacitacion


class FeedBack(models.Model):
    TIPO = (
        ('CL', 'Cliente'),
        ('PR', 'Proveedor'),
    )
    tipo = models.CharField(choices=TIPO, max_length=2, null=True, blank=True)
    mensaje = models.TextField()
    valoracion = models.PositiveIntegerField(null=True, blank=True)
    proveedor = models.ForeignKey(ProveedorServicio, null=True, blank=True, on_delete=models.CASCADE)
    capacitacion = models.ForeignKey(Capacitacion, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.mensaje

turismo/proveedor/models.py
from django.db import models

from util.models import AbstractDireccion


class Servicio(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre


class Beneficio(models.Model):
    nombre = models.CharField(max_length=250)
    puntos = models.PositiveIntegerField(default=1)
    servicio = models.ForeignKey(Servicio, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class ProveedorServicio(AbstractDireccion):
    class Meta:
        verbose_name_plural = 'Proveedores'

    nombre = models.CharField(max_length=250)
    cuit= models.CharField('CUIT', max_length=11, unique=True, null=True, blank=True)
    telefono = models.BigIntegerField('Número de Teléfono', null=True, blank=True)
    puntos = models.PositiveIntegerField(default=0, blank=True)
    historico_puntos = models.PositiveIntegerField(default=0, blank=True)
    servicio = models.ManyToManyField(Servicio)

    def __str__(self):
        return self.nombre

    def incrementar_puntos(self, puntos_incremento):
        self.puntos += puntos_incremento
        self.historico_puntos += puntos_incremento
        print('fefe')
        self.save()

    def decrementar_puntos(self, puntos_decremento):
        if self.puntos < puntos_decremento:
            return False
        self.puntos -= puntos_decremento
        self.save()
        return True

turismo/servicio/models.py
from django.db import models

# Create your models here.

turismo/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from proveedor.models import Proveedor


class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
        ordering = ('username', 'last_name', 'first_name')

    TIPO = (
        ('ADM', 'Administrador'),
        ('PST', 'Proveedor de Servicio Turístico'),
    )
    tipo = models.CharField(choices=TIPO, max_length=3, null=True, blank=True)
    proveedor = models.OneToOneField(
        Proveedor,
        null=True, blank=True,
        related_name='user_proveedor',
        on_delete=models.PROTECT
    )

USERNAME_FIELD = 'username'

turismo/util/models.py
from django.db import models
from django.contrib.gis.db import models as models_gis


class Departamento(models.Model):

    class Meta:
        ordering = ('nombre',)
        verbose_name_plural = ('Departamentos')

    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre


class Localidad(models.Model):

    class Meta:
        ordering = ('nombre',)
        verbose_name_plural = ('Localidades')

    nombre = models.CharField(max_length=100)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    cod_postal = models.IntegerField(null=True, blank=True, default=None)

    def __str__(self):
        return self.nombre


class AbstractDireccion(models.Model):

    class Meta:
        abstract = True

    nombre_dir = models.CharField(
        'Nombre de Calle',
        max_length=100,
        null=True, blank=True
    )
    numero_dir = models.PositiveIntegerField(
        'Número de Calle',
        null=True, blank=True
    )
    localidad = models.ForeignKey(Localidad, null=True, blank=True, on_delete=models.CASCADE)
    ubicacion = models_gis.PointField(null=True, blank=True)

turismo/pagina/forms.py
from django import forms
from . import models


class FeedBackFormCliente(forms.ModelForm):
    class Meta:
        model = models.FeedBack
        exclude = ('tipo', 'capacitacion')

    valoracion = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])


class FeedBackFormProveedor(forms.ModelForm):
    class Meta:
        model = models.FeedBack
        exclude = ('tipo', 'proveedor')

    valoracion = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])

turismo/proveedor/forms.py
from django import forms
from . import models

turismo/asistencia/views.py
from django.shortcuts import render

# Create your views here.

turismo/capacitacion/views.py
from django.shortcuts import render

# Create your views here.

turismo/pagina/views.py
from django.views.generic import TemplateView, CreateView
from proveedor.models import ProveedorServicio, Servicio, Beneficio
from . import models, forms


class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        proveedores = ProveedorServicio.objects.all()
        context.update(
            proveedores=proveedores,
        )
        return context

class Calendario(TemplateView):
    template_name = 'pagina/calendario.html'



class Proveedor(TemplateView):
    template_name = 'pagina/proveedor.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        beneficios = Beneficio.objects.all().values('nombre')
        context.update(
            beneficios=beneficios,
        )
        return context


class FeedbackClientesView(CreateView):
    model = models.FeedBack
    form_class = forms.FeedBackFormCliente
    template_name = 'pagina/feedback-clientes.html'
    success_url = '/'
    def form_valid(self, form):
        object = form.save(commit=True)
        object.tipo = 'CL'
        object.save()
        return super().form_valid(form)


class FeedbackProveedoresView(CreateView):
    model = models.FeedBack
    form_class = forms.FeedBackFormProveedor
    template_name = 'pagina/feedback-proveedores.html'
    success_url = '/'

    def form_valid(self, form):
        object = form.save(commit=True)
        object.tipo = 'PR'
        object.save()
        return super().form_valid(form)

turismo/proveedor/views.py
from django.shortcuts import render

# Create your views here.

turismo/servicio/views.py
from django.shortcuts import render

# Create your views here.

turismo/user/views.py
from django.shortcuts import render

# Create your views here.

turismo/util/views.py
from django.shortcuts import render

# Create your views here.

turismo/pagina/templates/pagina/calendario.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">

         <!-- Card content -->
          <div class="card-body"><h4>Calendario de Capacitaciones</h4>
            <div class="d-flex justify-content-center">

                <img class="center" src="{% static 'img/calendar.jpg' %}" width="70%" height="70%" alt="">
            </div>
          </div>

        </div>
        
    </div>
</div>

{% endblock %}

turismo/pagina/templates/pagina/feedback-clientes.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block css %}
    <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'home:feedback-clientes' %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

turismo/pagina/templates/pagina/feedback-proveedores.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block css %}
    <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'home:feedback-proveedores' %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

turismo/pagina/templates/pagina/proveedor.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block header %}
<header>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar ">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="/">
                <strong class="blue-text">Mejoremos y Punto</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent" style="">
                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                          aria-expanded="false">FeedBack</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href="{% url 'home:feedback-proveedores'%}">FeedBack Proveedores</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                          aria-expanded="false">Usuario Proveedor</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href="#">Perfil</a>
                            <a class="dropdown-item" href="#">Cerrar Sesión</a>
                        </div>
                    </li>
                </ul>


            </div>

        </div>
    </nav>
    <!-- Navbar -->

</header>
<!--Main Navigation-->
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">

         <!-- Card content -->
          <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h4 class="card-title">Puntos Para Canjear</h4>
                    <h4><span class="badge badge-success">23423</span></h4>
                </div>
                <div class="col-md-6">
                    <h4 class="card-title">Historial de Puntos</h4>
                    <h4><span class="badge badge-primary">2148732</span></h4>
                </div>
            </div>
          </div>

        </div>
        <br>
        <div class="card">

         <!-- Card content -->
          <div class="card-body">

            <!-- Title -->
            <h4 class="card-title">Canjear Puntos</h4>

              <select class="mdb-select md-form">
                  <option value="" disabled selected>Seleccionar Beneficio</option>
                  {% for b in beneficios %}
                    <option value="{{b.nombre}}">{{b.nombre}}</option>
                  {% endfor %}
                </select>

            <a href="#" class="btn btn-primary">Canjear</a>
          </div>

        </div>
    </div>
</div>

{% endblock %}
{% block js %}
<script>
        $(document).ready(function() {
         $('.mdb-select').materialSelect();
        });
</script>

{% endblock %}

turismo/templates/base.html
{% load staticfiles %}
{% load pwa %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Mejoremos y Punto</title>
        {% progressive_web_app_meta %}
        <link rel="stylesheet" href="{% static 'font/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        {% block css %} {% endblock %}
    </head>

    <body>
        {% block header %}
            {% include 'header.html' %}
        {% endblock %}

        <main class="mt-5 pt-5">
            <div class="container">
                {% block content %} {% endblock %}
            </div>
        </main>
        
        {% include 'footer.html' %}

        <!-- SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
        <script src="{% static 'leaflet/leaflet.js' %}"></script>
        <script type="text/javascript" src="{% static 'serviceworker/idb.js' %}"></script>
        <script type="text/javascript" src="{% static 'serviceworker/idbop.js' %}"></script>
        {% block js %} {% endblock %}
    </body>
</html>

turismo/templates/detail-map.html
{% extends 'base.html' %}
{% block js %}
    <script>
    x = "{{object.ubicacion.x}}".replace(/,/g, '.')
    y = "{{object.ubicacion.y}}".replace(/,/g, '.')
    // initialize the map
    var map = L.map('map').setView([y, x], 16);
    // load a tile layer
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
      }).addTo(map);
    L.marker([y, x]).addTo(map)
        .bindPopup('{{object.nombre}}')
        .openPopup();
    </script>
{% endblock %}

turismo/templates/footer.html
<!--Footer-->
<br><br><br><br>
<footer class="page-footer text-center font-small mdb-color pink mt-4 wow fadeIn" style="visibility: visible; animation-name: fadeIn;">


    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2018 Innovation Quick Off
        <br>
    </div>
    <!--/.Copyright-->
</footer>

turismo/templates/header.html
{% load staticfiles %}

<header>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar ">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="/">
                <strong class="blue-text"><img src="{% static 'img/cerebrito.jpg' %}" width="5%" alt="">Mejoremos y Punto</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent" style="">
                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <a href="{% url 'home:calendario' %}" class="nav-link">Calendario</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                          aria-expanded="false">FeedBack</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href="{% url 'home:feedback-clientes'%}">FeedBack Clientes</a>
                        </div>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
    <!-- Navbar -->

</header>
<!--Main Navigation-->

turismo/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <p class="h3 my-4">Proveedores de Servicios Turísticos</p>
        <div class="row justify-content-around">
            {% for proveedor in proveedores %}

                <div class="card col col-12 col-md-3">
                    <img class="card-img-top" src="{% static 'img/turismo.jpg' %}" alt="{{proveedor.nombre}}">

                    <!-- Card content -->
                    <div class="card-body">
                        <!-- Title -->
                        <h4 class="card-title"><a>{{proveedor.nombre}}</a></h4>
                        <!-- Text -->

                        {% for s in proveedor.servicio.all %}
                            <span class="badge badge-dark">{{s}}</span>
                        {% endfor %}
                        <br>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
        <br>
        <div class="card col-md-12">
            <div class="card-header font-weight-bold">
                <span><i class="fa fa-map-marker"></i> Mapa de Proveedores Turísticos</span>
            </div>

            <!--Card content-->
            <div class="card-body" id="map" style="height: 30%;"></div>
        </div>
    </div>
</div>
     
{% endblock %}

{% block js %}
    <script>
    var locations = [
		["LOCATION_2",-28.464006, -65.801610],
		["LOCATION_3",-28.460989, -65.799585],
		["LOCATION_4",-28.471579, -65.792626],
		["LOCATION_4",-28.472817, -65.788983],
		];

        var map = L.map('map').setView([-28.462761, -65.797925], 13);
        mapLink =
            '<a href="http://openstreetmap.org">OpenStreetMap</a>';
        L.tileLayer(
            'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; ' + mapLink + ' Contributors',
            maxZoom: 18,
            }).addTo(map);

		for (var i = 0; i < locations.length; i++) {
			marker = new L.marker([locations[i][1],locations[i][2]])
				.bindPopup(locations[i][0])
				.addTo(map);
		}
    </script>
{% endblock %}

turismo/templates/layout.html
{% load staticfiles %}
{% load pwa %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.png' %}" />
    <title>{% block title %}{% endblock %}</title>
    {% progressive_web_app_meta %}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121873025-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-121873025-1');
    </script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
    integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
   integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
   crossorigin=""></script>
</head>

<body>
    {% block navbar %}
    {% endblock %}

    <div class="limiter">
        <div class="container-login100">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <nav class="navbar fixed-bottom">
        <div class="row justify-content-md-center">
            <div class="col-md-12" style="margin-left:250%;">
                <a href="http://nextinnovationlab.com" style="color:rgb(78, 78, 78);">
                    Developed By <img class="m-x-auto" width="12%" src="{% static 'images/next-new-logo.png' %}" alt="Logo Next Innovation Lab">
                </a>
            </div>
        </div>
    </nav>
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

turismo/templates/mapwidgets/google-point-field-widget.html
{% extends "mapwidgets/google-point-field-widget.html" %}

{% block javascript %}
    <script type="application/javascript">
        (function($) {
            var mapOptions = JSON.parse("{{ options|escapejs }}");
            var fieldValue = JSON.parse("{{ field_value|escapejs }}");
            {% if not is_formset_empty_form_template %}
                var widgetData = JSON.parse("{{ js_widget_data|escapejs }}");
                var wrapElemSelector = widgetData.wrapElemSelector;
                var mapElemID = widgetData.mapElemID;
                var googleAutoInputID = widgetData.googleAutoInputID;
                var locationInputID = widgetData.locationInputID;
                var mapWidgetOptions = {
                    locationInput: $(locationInputID),
                    wrapElemSelector: wrapElemSelector,
                    locationFieldValue: fieldValue,
                    mapElement: document.getElementById(mapElemID),
                    mapCenterLocationName: mapOptions.mapCenterLocationName,
                    mapCenterLocation: mapOptions.mapCenterLocation,
                    coordinatesOverlayToggleBtn: $(".mw-btn-coordinates", wrapElemSelector),
                    coordinatesOverlayDoneBtn: $(".mw-btn-coordinates-done", wrapElemSelector),
                    coordinatesOverlayInputs: $(".mw-overlay-input", wrapElemSelector),
                    coordinatesOverlay: $(".mw-coordinates-overlay", wrapElemSelector),
                    myLocationBtn: $(".mw-btn-my-location", wrapElemSelector),
                    addressAutoCompleteInput: document.getElementById(googleAutoInputID),
                    deleteBtn: $(".mw-btn-delete", wrapElemSelector),
                    addMarkerBtn: $(".mw-btn-add-marker", wrapElemSelector),
                    loaderOverlayElem: $(".mw-loader-overlay", wrapElemSelector),
                    zoom: mapOptions.zoom,
                    markerFitZoom: mapOptions.markerFitZoom,
                    GooglePlaceAutocompleteOptions: mapOptions.GooglePlaceAutocompleteOptions,
                    markerCreateTriggerNameSpace: "google_point_map_widget:marker_create",
                    markerChangeTriggerNameSpace: "google_point_map_widget:marker_change",
                    markerDeleteTriggerNameSpace: "google_point_map_widget:marker_delete",
                    placeChangedTriggerNameSpace: "google_point_map_widget:place_changed"
                };
                var widget = new DjangoGooglePointFieldWidget(mapWidgetOptions);
            {% else %}
                var widgetDataTemplate = JSON.parse("{{ js_widget_data|escapejs }}");
                var widgetGenerater = new DjangoMapWidgetGenerater({
                    "widgetDataTemplate": widgetDataTemplate,
                    "mapOptions": mapOptions,
                    "fieldValue": fieldValue
                });
            {% endif %}
        })(jQuery || django.jQuery);
    </script>
{% endblock javascript %}